import { Inter } from 'next/font/google'
import './globals.css'
import NavigationBar from '@/components/navigationbar'
import Providers from '@/components/Providers'

import 'bootstrap/dist/css/bootstrap.min.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'App Frontend',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Providers>
          <NavigationBar/>
        </Providers>
        {children}
      </body>
    </html>
  )
}
